# Yaml "Validator": https://www.yamllint.com/

# Yaml allows comments

String Syntax 1: "Example String"
String Syntax 2: Example String
MultiLine String: | 
First Line
Second Line
MultiLine String as a SingleLine: >
First Line
Second Line
All these will be read as on line
Integer Number: "-12"
Float Number: 3.4
Sci-Notation Float: 1.2e10
Boolean Syntax 1: true
Boolean Syntax 2: yes
Boolean Syntax 3: on
Null Value: Null
Array Syntax 1: [5, 6, 7]
Array Syntax 2:
  - 5
  - 6
  - 7
Array Of Objects:
  First: it's a list of
  Second: key-value pairs, Unlike
  Third: the non-object/array list above
My Object:
  scripts:
    start: node app.js
  dependencies:
    express: "4.17.1"
---
# k8s manifests

apiVersion: my_version

# pods

kind_1: my_pod
metadata_1:
  name_1: some_pod_name
spec_1:
  containers_1:
    - name_1: some_pod_name_could_be_another
      image_1: my_pod_image

# replicasets